plugins {
    id 'java'
    id 'jacoco'
}

dependencies {
    implementation project(':model')
}

group = 'co.com.pragma.solicitud'
version = '1.0.0'

repositories {
    mavenCentral()
}

tasks.test {
    useJUnitPlatform() // importante para JUnit 5
    finalizedBy tasks.jacocoTestReport // generar reporte despues de test
}

jacoco {
    toolVersion = "0.8.10"
}

tasks.jacocoTestReport {
    dependsOn tasks.test
    reports {
        xml.required.set(true)
        csv.required.set(false)
        html.required.set(true)
        html.outputLocation.set(layout.buildDirectory.dir("reports/jacoco/html"))
    }
}