server:
  port: ${SERVER_PORT_REQ:8081}
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  webflux:
    base-path: /solicitud
  application:
    name: ${APP_NAME_REQ:cred-solicitud-svc}
  devtools:
    add-properties: false
  jackson:
    parser:
      STRICT_DUPLICATE_DETECTION: true
  profiles:
    include: null
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password:  ${SPRING_R2DBC_PASSWORD}
  sql.init.mode: "never"
  messages:
    basename: ${I18N_BASENAME_REQ:i18n/validation-messages}
    encoding: ${I18N_ENCODING_REQ:UTF-8}
    fallback-to-system-locale: false

adapters:
  r2dbc:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    database: ${DB_NAME:pragma_credi}
    schema: ${DB_SCHEMA:public}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:admin}

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080}

logging:
  level:
    co.com.pragma.solicitud.api: DEBUG

clients:
  user-service:
    base-url: ${USER_SERVICE_AUTH_BASE_URL:http://localhost:8080}

security:
  jwt:
    secret: ${JWT_SECRET:change-me-in-prod}
    ttl-seconds: ${JWT_TTL_SECONDS:3600}

aws:
  region: ${AWS_REGION:us-east-1}
  access-key: ${AWS_ACCESS_KEY_ID:dummy}
  secret-key: ${AWS_SECRET_ACCESS_KEY:dummy}
  sqs:
    queue-url: ${AWS_SQS_QUEUE_NOTIFICATION_URL:dummy}
    incoming-queue:
      url: ${AWS_SQS_QUEUE_INCOMING_URL:dummy}
      is-fifo: true
    validation-queue:
      url: ${AWS_SQS_QUEUE_VALIDATION_URL:dummy}
      is-fifo: true
    report-queue:
        url: ${AWS_SQS_QUEUE_REPORT_URL:dummy}
        is-fifo: true

outbox:
  poll-interval-ms: ${OUTBOX_POLL_INTERVAL_MS:5000}
  batch-size: ${OUTBOX_BATCH_SIZE:50}
  max-retries: ${OUTBOX_MAX_RETRIES:10}
  parallelism: ${OUTBOX_PARALLELISM:5}

sqs:
  incoming:
    poll-interval-ms: ${SQS_INCOMING_POLL_INTERVAL_MS:5000}
    max-messages: ${SQS_INCOMING_MAX_MESSAGES:10}
    wait-seconds: ${SQS_INCOMING_WAIT_SECONDS:10}
    visibility-timeout: ${SQS_INCOMING_VISIBILITY_TIMEOUT:30}
    fifo:
      max-concurrent-groups: ${SQS_INCOMING_FIFO_MAX_CONCURRENT_GROUPS:4}